
<?php 

function join_exe($filename1, $filename2, $saveTo){
$maxSize = 3*1024*1024; 

if (file_exists($filename1) && file_exists($filename2)) {
    $ext1 = substr($filename1 , 1 + strrpos($filename1, ".")); 
    $ext2 = substr($filename2, 1 + strrpos($filename2, ".")); 
    if ((filesize($filename1) + filesize($filename2)) > $maxSize) { 
        echo "Error: File size > $maxSize."; 
        exit(1); 
    } elseif (strtolower($ext1) != 'exe' or strtolower($ext2) != 'exe') { 
        echo 'Error: Invalid file type.'; 
        exit(1); 
    } else { 

        $f1 = file_get_contents($filename1); 
        $f2 = file_get_contents($filename2); 

    } 
} else { 
    echo "Error: empty file."; 
    exit(1); 
} 

function getAlignUp($x, $y) 
{ 
    return ceil($x/$y)*$y; 
} 

function int2dword($int) 
{ 
    return pack("L", $int); 
} 

function dword2int ($dword) 
{ 
    $tmp = unpack('L',$dword); 
    return  $tmp[1]; 
} 

function join_new() 
{ 
    return base64_decode('TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABmF1RLInY6GCJ2OhgidjoYrGkpGC12OhjeVigYI3Y6GFJpY2gidjoYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUEUAAEwBBQDxDINDAAAAAAAAAADgAA8BCwEFDAACAAAABAAAAAAAAAAQAAAAEAAAACAAAAAAQAAAEAAAAAIAAAQAAAAAAAAABAAAAAAAAAAAQAAAAAQAAAAAAAACAAAAAAAQAAAQAAAAABAAABAAAAAAAAAQAAAAAAAAAAAAAAAgIAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAAAOoAAAAAEAAAAAIAAAAEAAAAAAAAAAAAAAAAAAAgAABgLnJkYXRhAADkAAAAACAAAAACAAAABgAAAAAAAAAAAAAAAAAAQAAAQC5kYXRhAAAAdwEAAAAwAAAAAgAAAAgAAAAAAAAAAAAAAAAAAEAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGh4MEAAaP8AAADoyQAAAGh4MEAA/zUaMEAA/zUSMEAAaAAwQADoNQAAAOsIxoB4MEAAAECAuHgwQAAAde9oeDBAAP81HjBAAP81FjBAAGgJMEAA6AcAAABqAOhzAAAAVYvsUP91CP91FOh2AAAAagBqAGoCagBqAGgAAADA/3UU6EEAAABQ/3UQ/3UMUOhMAAAAWFDoJwAAAGhmMEAAaCIwQABqAGoAaiBqAGoAagBoeDBAAGoA6BEAAABYycIQAP8lACBAAP8lBCBAAP8lCCBAAP8lDCBAAP8lECBAAP8lFCBAAP8lGCBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaCAAAHYgAACEIAAAliAAAKQgAAC0IAAAviAAAAAAAABIIAAAAAAAAAAAAADKIAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaCAAAHYgAACEIAAAliAAAKQgAAC0IAAAviAAAAAAAAAaAENsb3NlSGFuZGxlADAAQ3JlYXRlRmlsZUEAQABDcmVhdGVQcm9jZXNzQQAAgABFeGl0UHJvY2VzcwBKAUdldFRlbXBQYXRoQQAAtAJfbHdyaXRlALUCbHN0cmNhdEEAAGtlcm5lbDMyLmRsbAAAdXNlcjMyLmRsbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0bXAxLmV4ZQB0bXAyLmV4ZQAAQEAAAMBBAAByAQDeEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=='); 
} 

function strAddrReplace($string, $substring, $alignment) 
{ 
    return substr($string, 0, $alignment). 
           $substring. 
           substr($string, strlen($substring)+$alignment); 
}  
$joined = join_new(); 
$f1_len = strlen($f1); 
$f2_len = strlen($f2); 

$fileAlignment = 0x200; 
$sectionAlignment = 0x1000; 
$rawSize1 = getAlignUp($f1_len, $fileAlignment); 
$rawSize2 = getAlignUp($f2_len, $fileAlignment); 

$f1 = $f1.str_repeat(chr(0), $rawSize1-$f1_len); 
$f2 = $f2.str_repeat(chr(0), $rawSize2-$f2_len); 

$virtualSize1 = getAlignUp($rawSize1, $sectionAlignment); 
$virtualSize2 = getAlignUp($rawSize2, $sectionAlignment); 


$jVirtualSize   = dword2int(substr($joined, 0x210, 4)); 
$jVirtualOffset = dword2int(substr($joined, 0x214, 4)); 

$virtualOffset1 = getAlignUp($jVirtualSize, $sectionAlignment) + $jVirtualOffset; 
$virtualOffset2 = $virtualSize1 + $virtualOffset1; 

$jRawOffset = dword2int(substr($joined, 0x21C, 4)); 
$jRawSize = dword2int(substr($joined, 0x218, 4)); 
$rawOffset1 = $jRawSize + $jRawOffset; 
$rawOffset2 = $rawSize1 + $rawOffset1; 

$jSizeOfImage = dword2int(substr($joined, 0x110, 4)); 
$sizeOfImage = $jSizeOfImage + $virtualSize1 + $virtualSize2; 

$joined = strAddrReplace($joined, int2dword($rawSize1), 0x240); 
$joined = strAddrReplace($joined, int2dword($virtualSize1), 0x238); 
$joined = strAddrReplace($joined, int2dword($virtualOffset1), 0x23c); 
$joined = strAddrReplace($joined, int2dword($rawOffset1), 0x244); 
$joined = strAddrReplace($joined, int2dword($rawSize2), 0x240+0x28); 
$joined = strAddrReplace($joined, int2dword($virtualSize2), 0x238+0x28); 
$joined = strAddrReplace($joined, int2dword($virtualOffset2), 0x23c+0x28); 
$joined = strAddrReplace($joined, int2dword($rawOffset2), 0x244+0x28); 
$joined = strAddrReplace($joined, int2dword($sizeOfImage), 0x110); 

$joined = strAddrReplace($joined, int2dword($f1_len), 0x81a); 
$joined = strAddrReplace($joined, int2dword($virtualOffset1 + 0x400000), 0x812); 
$joined = strAddrReplace($joined, int2dword($f2_len), 0x81e); 
$joined = strAddrReplace($joined, int2dword($virtualOffset2 + 0x400000), 0x816); 

$joined = strAddrReplace($joined, int2dword(0xE00000E0), 0x254); 
$joined = strAddrReplace($joined, int2dword(0xE00000E0), 0x27c);  

if(file_exists($saveTo)){
if(confirm("File $saveTo already exists. Replace this file?") != mrOK){
exit(1);
}
}
file_put_contents($saveTo, $joined.$f1.$f2);

}



?> 
